# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Lynkeus\_Modules\GK AI Smart Parking Solution\Parking_2024\Forms\live_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Live_view(object):
    def setupUi(self, Live_view):
        Live_view.setObjectName("Live_view")
        Live_view.resize(1300, 814)
        Live_view.setMinimumSize(QtCore.QSize(0, 0))
        Live_view.setStyleSheet("QWidget#Live_view{\n"
"background:#1d1d1d;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Live_view)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Live_view)
        self.widget.setMinimumSize(QtCore.QSize(0, 80))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget.setStyleSheet("\n"
"\n"
"*{\n"
"font-family: century gothic;\n"
"}\n"
"QWidget#widget{\n"
"background:#1d1d1d;\n"
"}\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0.482, y1:0.3, x2:0.482224, y2:0, stop:0.15 rgba(0, 0, 0, 147), stop:1 rgba(255, 255, 255, 25));\n"
"/*background:#2d89ef;*/\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:1px solid rgba(45, 137, 239,100);\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:none;")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setLineWidth(3)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icon/icon/dome_camera_80px_32.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"background:none;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(3)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btn_home = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_home.sizePolicy().hasHeightForWidth())
        self.btn_home.setSizePolicy(sizePolicy)
        self.btn_home.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_home.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_home.setStyleSheet("")
        self.btn_home.setObjectName("btn_home")
        self.horizontalLayout_5.addWidget(self.btn_home)
        spacerItem1 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btn_camera_add = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.btn_camera_add.sizePolicy().hasHeightForWidth())
        self.btn_camera_add.setSizePolicy(sizePolicy)
        self.btn_camera_add.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_camera_add.setObjectName("btn_camera_add")
        self.horizontalLayout_5.addWidget(self.btn_camera_add)
        self.btn_config = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.btn_config.sizePolicy().hasHeightForWidth())
        self.btn_config.setSizePolicy(sizePolicy)
        self.btn_config.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_config.setObjectName("btn_config")
        self.horizontalLayout_5.addWidget(self.btn_config)
        self.btn_map = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_map.sizePolicy().hasHeightForWidth())
        self.btn_map.setSizePolicy(sizePolicy)
        self.btn_map.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_map.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_map.setStyleSheet("")
        self.btn_map.setObjectName("btn_map")
        self.horizontalLayout_5.addWidget(self.btn_map)
        spacerItem2 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btn_about = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.btn_about.sizePolicy().hasHeightForWidth())
        self.btn_about.setSizePolicy(sizePolicy)
        self.btn_about.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_about.setObjectName("btn_about")
        self.horizontalLayout_5.addWidget(self.btn_about)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(Live_view)
        self.stackedWidget.setStyleSheet("\n"
"\n"
"*{\n"
"font-family: century gothic;\n"
"}\n"
"QWidget#page{\n"
"background:#1d1d1d;\n"
"}\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0.482, y1:0.3, x2:0.482224, y2:0, stop:0.15 rgba(0, 0, 0, 147), stop:1 rgba(255, 255, 255, 25));\n"
"/*background:#2d89ef;*/\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:1px solid rgba(45, 137, 239,100);\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.live_view = QtWidgets.QWidget()
        self.live_view.setObjectName("live_view")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.live_view)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.live_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setStyleSheet("background:#1d1d1d;")
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 969, 578))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaWidgetContents.setStyleSheet("background:#1d1d1d;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(7, 7, 7, 7)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layout = QtWidgets.QGridLayout()
        self.layout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.layout.setContentsMargins(7, 7, 7, 7)
        self.layout.setSpacing(5)
        self.layout.setObjectName("layout")
        self.gridLayout_2.addLayout(self.layout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.widget_devicemgr = QtWidgets.QFrame(self.live_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_devicemgr.sizePolicy().hasHeightForWidth())
        self.widget_devicemgr.setSizePolicy(sizePolicy)
        self.widget_devicemgr.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_devicemgr.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_devicemgr.setStyleSheet("*{\n"
"font-family: century gothic;\n"
"}\n"
"QWidget#widget{\n"
"background:#1d1d1d;\n"
"}\n"
"\n"
"QLabel{\n"
"\n"
"color:white;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.widget_devicemgr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.widget_devicemgr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.widget_devicemgr.setObjectName("widget_devicemgr")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_devicemgr)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_devicemgr)
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignTop)
        self.line = QtWidgets.QFrame(self.widget_devicemgr)
        self.line.setStyleSheet("background-color:rgba(100,100,255,100);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formFrame = QtWidgets.QFrame(self.widget_devicemgr)
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.formFrame)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.deviceName = QtWidgets.QLineEdit(self.formFrame)
        self.deviceName.setObjectName("deviceName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deviceName)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.add_ip = QtWidgets.QLineEdit(self.formFrame)
        self.add_ip.setObjectName("add_ip")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.add_ip)
        self.label_8 = QtWidgets.QLabel(self.formFrame)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.add_username = QtWidgets.QLineEdit(self.formFrame)
        self.add_username.setObjectName("add_username")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.add_username)
        self.label_9 = QtWidgets.QLabel(self.formFrame)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.add_password = QtWidgets.QLineEdit(self.formFrame)
        self.add_password.setObjectName("add_password")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.add_password)
        self.label_11 = QtWidgets.QLabel(self.formFrame)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.add_location = QtWidgets.QLineEdit(self.formFrame)
        self.add_location.setObjectName("add_location")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.add_location)
        self.verticalLayout.addWidget(self.formFrame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.widget_devicemgr)
        self.frame_2.setStyleSheet("border:1px solid rgba(255,255,255,0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_add = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setMinimumSize(QtCore.QSize(250, 30))
        self.btn_add.setMaximumSize(QtCore.QSize(200, 36))
        self.btn_add.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0.482, y1:0.3, x2:0.482224, y2:0, stop:0.15 rgba(0, 0, 0, 147), stop:1 rgba(255, 255, 255, 25));\n"
"/*background:#2d89ef;*/\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:1px solid rgba(45, 137, 239,100);\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"")
        self.btn_add.setDefault(False)
        self.btn_add.setFlat(False)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout_3.addWidget(self.btn_add)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.btn_lukao = QtWidgets.QPushButton(self.widget_devicemgr)
        self.btn_lukao.setMinimumSize(QtCore.QSize(20, 50))
        self.btn_lukao.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_lukao.setStyleSheet("QPushButton{\n"
"color:rgba(255,255,255,100);\n"
"background-color:rgba(70,70,70,100);\n"
"}")
        self.btn_lukao.setObjectName("btn_lukao")
        self.verticalLayout.addWidget(self.btn_lukao, 0, QtCore.Qt.AlignLeft)
        self.label_10 = QtWidgets.QLabel(self.widget_devicemgr)
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:white;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.line_2 = QtWidgets.QFrame(self.widget_devicemgr)
        self.line_2.setStyleSheet("background-color:rgba(100,100,255,100);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.frame_modify = QtWidgets.QFrame(self.widget_devicemgr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_modify.sizePolicy().hasHeightForWidth())
        self.frame_modify.setSizePolicy(sizePolicy)
        self.frame_modify.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_modify.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_modify.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_modify.setObjectName("frame_modify")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_modify)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_modify, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.btn_devicemgr = QtWidgets.QPushButton(self.widget_devicemgr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_devicemgr.sizePolicy().hasHeightForWidth())
        self.btn_devicemgr.setSizePolicy(sizePolicy)
        self.btn_devicemgr.setMinimumSize(QtCore.QSize(256, 40))
        self.btn_devicemgr.setMaximumSize(QtCore.QSize(256, 40))
        self.btn_devicemgr.setStyleSheet("QPushButton{\n"
"background-color: rgba(110, 110, 252,100);\n"
"/*background:#2d89ef;*/\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:1px solid rgba(45, 137, 239,100);\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"")
        self.btn_devicemgr.setObjectName("btn_devicemgr")
        self.verticalLayout.addWidget(self.btn_devicemgr, 0, QtCore.Qt.AlignHCenter)
        self.btn_cleardb = QtWidgets.QPushButton(self.widget_devicemgr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cleardb.sizePolicy().hasHeightForWidth())
        self.btn_cleardb.setSizePolicy(sizePolicy)
        self.btn_cleardb.setMinimumSize(QtCore.QSize(256, 40))
        self.btn_cleardb.setMaximumSize(QtCore.QSize(256, 40))
        self.btn_cleardb.setStatusTip("")
        self.btn_cleardb.setWhatsThis("")
        self.btn_cleardb.setStyleSheet("QPushButton{\n"
"background-color: rgba(252, 110, 110,100);\n"
"/*background:#2d89ef;*/\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:1px solid rgba(45, 137, 239,100);\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"")
        self.btn_cleardb.setObjectName("btn_cleardb")
        self.verticalLayout.addWidget(self.btn_cleardb, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.widget_devicemgr)
        self.stackedWidget.addWidget(self.live_view)
        self.map_view = QtWidgets.QWidget()
        self.map_view.setObjectName("map_view")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.map_view)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_123 = QtWidgets.QWidget(self.map_view)
        self.widget_123.setStyleSheet("border:1px solid #3f4045;\n"
"border-radius:10px;")
        self.widget_123.setObjectName("widget_123")
        self.horizontalLayout_99 = QtWidgets.QHBoxLayout(self.widget_123)
        self.horizontalLayout_99.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_99.setSpacing(5)
        self.horizontalLayout_99.setObjectName("horizontalLayout_99")
        self.widget_124 = QtWidgets.QWidget(self.widget_123)
        self.widget_124.setMinimumSize(QtCore.QSize(220, 0))
        self.widget_124.setMaximumSize(QtCore.QSize(260, 16777215))
        self.widget_124.setStyleSheet("")
        self.widget_124.setObjectName("widget_124")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_124)
        self.verticalLayout_21.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_21.setSpacing(5)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_80 = QtWidgets.QLabel(self.widget_124)
        self.label_80.setStyleSheet("background:transparent;\n"
"color:rgba(255, 255, 255, 0.8);\n"
"font-size:12px;\n"
"font-weight:500;\n"
"border:none;")
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_59.addWidget(self.label_80)
        self.terrian_view_btn = QtWidgets.QPushButton(self.widget_124)
        self.terrian_view_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.terrian_view_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.terrian_view_btn.setStyleSheet("QPushButton {    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"    font-size:10px;\n"
"    font-weight:bold;\n"
"    padding:5px 10px 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.terrian_view_btn.setIconSize(QtCore.QSize(31, 42))
        self.terrian_view_btn.setObjectName("terrian_view_btn")
        self.horizontalLayout_59.addWidget(self.terrian_view_btn)
        self.setellite_view_btn = QtWidgets.QPushButton(self.widget_124)
        self.setellite_view_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.setellite_view_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.setellite_view_btn.setStyleSheet("QPushButton {    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"    font-size:10px;\n"
"    font-weight:bold;\n"
"    padding:5px 10px 5px 10px;\n"
"}\n"
"\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton:pressed{    \n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.setellite_view_btn.setIconSize(QtCore.QSize(31, 42))
        self.setellite_view_btn.setObjectName("setellite_view_btn")
        self.horizontalLayout_59.addWidget(self.setellite_view_btn)
        self.verticalLayout_21.addLayout(self.horizontalLayout_59)
        self.map_scroll_widget = QtWidgets.QScrollArea(self.widget_124)
        self.map_scroll_widget.setStyleSheet("border:none;")
        self.map_scroll_widget.setWidgetResizable(True)
        self.map_scroll_widget.setObjectName("map_scroll_widget")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 250, 517))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.map_scroll_widget.setWidget(self.scrollAreaWidgetContents_9)
        self.verticalLayout_21.addWidget(self.map_scroll_widget)
        self.horizontalLayout_99.addWidget(self.widget_124)
        self.gridLayout_5.addWidget(self.widget_123, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.map_view)
        self.horizontalLayout_6.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.widget_2 = QtWidgets.QWidget(Live_view)
        self.widget_2.setStyleSheet("\n"
"\n"
"*{\n"
"font-family: century gothic;\n"
"}\n"
"QLabel{\n"
"color:rgb(142, 154, 159);\n"
"background-color:none;\n"
"}\n"
"QLineEdit{\n"
"color:rgb(142, 154, 159);\n"
"background:none;\n"
"}\n"
"QWidget#widget_2{\n"
"background:#1d1d1d;\n"
"}\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0.482, y1:0.3, x2:0.482224, y2:0, stop:0.15 rgba(0, 0, 0, 147), stop:1 rgba(255, 255, 255, 25));\n"
"/*background:#2d89ef;*/\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:1px solid rgba(45, 137, 239,100);\n"
"border-radius:0px;\n"
"color:white;\n"
"font-weight:bold;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridFrame_2 = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFrame_2.sizePolicy().hasHeightForWidth())
        self.gridFrame_2.setSizePolicy(sizePolicy)
        self.gridFrame_2.setStyleSheet("QFrame#gridFrame_2{\n"
"background:none;\n"
"border:1px solid blue;\n"
"}")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout.setContentsMargins(7, 7, 7, 7)
        self.gridLayout.setObjectName("gridLayout")
        self.line_All_CPU = QtWidgets.QLineEdit(self.gridFrame_2)
        self.line_All_CPU.setFrame(False)
        self.line_All_CPU.setObjectName("line_All_CPU")
        self.gridLayout.addWidget(self.line_All_CPU, 1, 1, 1, 1)
        self.line_VMS_CPU = QtWidgets.QLineEdit(self.gridFrame_2)
        self.line_VMS_CPU.setFrame(False)
        self.line_VMS_CPU.setObjectName("line_VMS_CPU")
        self.gridLayout.addWidget(self.line_VMS_CPU, 0, 1, 1, 1)
        self.label_All_CPU = QtWidgets.QLabel(self.gridFrame_2)
        self.label_All_CPU.setObjectName("label_All_CPU")
        self.gridLayout.addWidget(self.label_All_CPU, 1, 0, 1, 1)
        self.label_VMS_CPU = QtWidgets.QLabel(self.gridFrame_2)
        self.label_VMS_CPU.setObjectName("label_VMS_CPU")
        self.gridLayout.addWidget(self.label_VMS_CPU, 0, 0, 1, 1)
        self.label_Memory = QtWidgets.QLabel(self.gridFrame_2)
        self.label_Memory.setObjectName("label_Memory")
        self.gridLayout.addWidget(self.label_Memory, 2, 0, 1, 1)
        self.line_Memory = QtWidgets.QLineEdit(self.gridFrame_2)
        self.line_Memory.setFrame(False)
        self.line_Memory.setObjectName("line_Memory")
        self.gridLayout.addWidget(self.line_Memory, 2, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.gridFrame_2)
        spacerItem5 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setMaximumSize(QtCore.QSize(0, 0))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icon/icon/Untitled-1.png"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.label_4 = QtWidgets.QLabel(Live_view)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"background-color: rgb(42, 54, 59);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)

        self.retranslateUi(Live_view)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Live_view)

    def retranslateUi(self, Live_view):
        _translate = QtCore.QCoreApplication.translate
        Live_view.setWindowTitle(_translate("Live_view", "Form"))
        self.label.setText(_translate("Live_view", "CCTV Based Restricted Area Monitoring System"))
        self.btn_home.setText(_translate("Live_view", "Home"))
        self.btn_camera_add.setText(_translate("Live_view", "Add Camera"))
        self.btn_config.setText(_translate("Live_view", "Configuration"))
        self.btn_map.setText(_translate("Live_view", "Map"))
        self.btn_about.setText(_translate("Live_view", "About"))
        self.label_3.setText(_translate("Live_view", "Device Manager"))
        self.label_6.setText(_translate("Live_view", "Device Name"))
        self.label_7.setText(_translate("Live_view", "IP"))
        self.label_8.setText(_translate("Live_view", "Usename"))
        self.label_9.setText(_translate("Live_view", "Password"))
        self.label_11.setText(_translate("Live_view", "Location"))
        self.btn_add.setText(_translate("Live_view", "Add"))
        self.btn_lukao.setText(_translate("Live_view", ">"))
        self.label_10.setText(_translate("Live_view", "Update Slots"))
        self.btn_devicemgr.setText(_translate("Live_view", "Device Manager"))
        self.btn_cleardb.setToolTip(_translate("Live_view", "<html><head/><body><p>Close All Videos</p></body></html>"))
        self.btn_cleardb.setText(_translate("Live_view", "Clear All Cameras"))
        self.label_80.setText(_translate("Live_view", "Camera List"))
        self.terrian_view_btn.setText(_translate("Live_view", "Terrain"))
        self.setellite_view_btn.setText(_translate("Live_view", "Satellite"))
        self.line_All_CPU.setText(_translate("Live_view", "0"))
        self.line_VMS_CPU.setText(_translate("Live_view", "0"))
        self.label_All_CPU.setText(_translate("Live_view", "All CPU State    :"))
        self.label_VMS_CPU.setText(_translate("Live_view", "VMS CPU State :"))
        self.label_Memory.setText(_translate("Live_view", "Memory State  :"))
        self.line_Memory.setText(_translate("Live_view", "0"))
        self.label_4.setText(_translate("Live_view", "Copyright©2024, Group 04. All rights reserved."))
import resource_rc
